[package]
name = "ferrobus_core"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
thiserror = "2.0"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json.workspace = true
csv = "1"
postcard = { version = "1.1", default-features = false, features = [
    "use-std",
] }
chrono.workspace = true
rstar = { version = "0.12", features = ["serde"] }
rustworkx-core = "0.17"
petgraph = { version = "0.8", features = ["serde-1"] }
hashbrown = { version = "0.16.0", features = ["serde"] }
fixedbitset = "0.5"
h3o = { version = "0.9.0", features = ["geo", "serde"] }
#osm4routing = { git = "https://github.com/rust-transit/osm4routing2.git" }
osm4routing = { git = "https://github.com/chingiztob/osm4routing2.git", branch = "switch_to_osmpbf" }
geo.workspace = true
geojson.workspace = true
rayon.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"

[dev-dependencies]
criterion = "0.8"
dotenvy = "0.15"

[[bench]]
name = "bench_main"
harness = false
