name: CodSpeed

on:
  push:
    branches:
      - "master" # or "master"
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

jobs:
  benchmarks:
    name: Run benchmarks
    # The hosted benchmark integration is configured for upstream.
    if: ${{ github.repository == 'chingiztob/ferrobus' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Install stable Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
            workspaces: .

      - name: Install dependencies
        run: uv sync --dev

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          mode: instrumentation
          run: uv run pytest --codspeed
          token: ${{ secrets.CODSPEED_TOKEN }}
